module.exports = {
  CONNECT: "connection",
  LOGIN: "LOGIN",
  CHAT: {
    MESSAGE: "MESSAGE",
    INITIAL_MESSAGES: "INITIAL_MESSAGES"
  },
  BETS: {
    INITIAL_BETS: "INITIAL_BETS",
    INITIAL_USER_BETS: "INITIAL_USER_BETS"
  },
  DICE: {
    ROLL: "ROLL",
    ROLL_RESULT: "ROLL_RESULT"
  }
};
